# https://kit.svelte.dev/docs/adapter-static#github-pages
name: Deploy to GitHub Pages

on:
  workflow_dispatch:
  push:
    branches: "main"

jobs:
  build_site:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: pmtiles
        run: |
          wget https://github.com/protomaps/go-pmtiles/releases/download/v1.23.1/go-pmtiles_1.23.1_Linux_x86_64.tar.gz && \
          tar -xvzf go-pmtiles_1.23.1_Linux_x86_64.tar.gz && mv pmtiles /usr/local/bin/

      - name: Update
        run: |
          make fonts
          make tiles

      - name: build
        env:
          BASE_URL: "/wildfires-2025"
        run: |
          npm run build

      - name: Upload Artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          path: "dist/"

  deploy:
    needs: build_site
    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4
